BSPIMX8M-3139: create PD24.1.0.rst BSP manual
phytec/doc-bsp-yocto pull request #146
Opened 2024-01-31 13:26 UTC by ymoog

For upcoming imx8mp mainline BSP release, add a manual.
This is done because the content and structure may be different from vendor releases. Since the plan is to move back to vendor release after the mainline release, we do not work on the head manual and branch off early.

2024-02-01 07:39 UTC, tremmet approved these changes

2024-02-01 07:39 UTC, tremmet commented on source/bsp/getting-started.rsti
> +format more complex systems. You can get `prebuilt Linux binaries of partup
would be "pre-built" even more correct?

2024-02-01 08:00 UTC, ymoog commented on source/bsp/getting-started.rsti
> +format more complex systems. You can get `prebuilt Linux binaries of partup
I don't know tbh. [Apparently not](https://dictionary.cambridge.org/dictionary/english/prebuilt)

2024-02-01 13:33 UTC, jremmert-phytec-iot requested changes
I think that customers could be confused by thinking that PD24.1.0 has been released already. Can we make this more obvious that is an unreleased BSP? Remember that everything gets published immediately, which was not the case before with our confluence setting.

Like e.g.:

- Adding a red warning box at the beginning of the manual. Maybe we can even refer to a doc that explains how customers could checkout this WIP BSP for testing? After all, whenever the reader consult Docs for released BSPs, they see those new and unreleased BSPs in the sidebar and that might raise their interest (which is a good thing I guess).
- Changing the manual Name to PD24.1.y from PD24.1.0. Once we release the manual we can change this.

What do you think?

2024-02-01 13:43 UTC, ymoog commented
> I think that customers could be confused by thinking that PD24.1.0 has been released already. Can we make this more obvious that is an unreleased BSP? Remember that everything gets published immediately, which was not the case before with our confluence setting.
> 
> Like e.g.:
> 
>     * Adding a red warning box at the beginning of the manual. Maybe we can even refer to a doc that explains how customers could checkout this WIP BSP for testing? After all, whenever the reader consult Docs for released BSPs, they see those new and unreleased BSPs in the sidebar and that might raise their interest (which is a good thing I guess).
> 
>     * Changing the manual Name to PD24.1.y from PD24.1.0. Once we release the manual we can change this.
> 
> 
> What do you think?

I agree it is a challenge to avoid confusion.

My suggestion is the following:
1. Create "feature" branch where all PR are merged to.
2. Use normal workflow for working on pd24.1.0
3. Merge feature branch into main -> tag it.

Then, no pd24 will be public at all. We have a pd24 draft that we can continously develop until release.
After release the feature branch is deleted so no complexity regarding multiple branches.

2024-02-01 13:49 UTC, jremmert-phytec-iot commented
Generally I like the idea of drafting the manuals of unreleased BSPs in the open. We also develop them in the open and customers can test them anytime. And if they test BSPs, a draft manual is a great advantage.

Of course they have to be aware of this, so a prominent marking of draft bsps should be sufficient IMO.

2024-02-02 09:32 UTC, BHahn42618 reviewed
I agree with Yannic. Creating a feature branch is probably the better idea, because if we released this to public, customers would probably expect everything in the manual to work, which is not the case. That could lead to more questions for the FAE/support, which we should probably avoid.
If customers want to checkout the development version (.y manifest) they can do so based on the chapter 5.4.2 in the PD23.1.0 or head manual, where it is documented how to checkout development states of upcoming releases.

2024-02-02 09:32 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/pd24.1.0.rst
> +.. include:: /bsp/imx8/development.rsti
You still need to rebase this to match this:
https://github.com/phytec/doc-bsp-yocto/pull/145/commits/71c580e191c3f2cf7f8c90118a3d6333f2630fc8#diff-1c7cbb8c30894749c3d2c91cfb28332d8d51bc4adb1c8e533f88b878fac3dacc

2024-02-05 09:56 UTC, jremmert-phytec-iot commented
>  [..] because if we released this to public, customers would probably expect everything in the manual to work, which is not the case. That could lead to more questions for the FAE/support, which we should probably avoid.

Yes, you have a point here. But with our existing approach, the upcoming release is already being public (HEAD Documents). Several weeks back with the PD23.1.0 imx8 release, we linked this documentation in the Phytec Website for the first time. So at this point we probably can not yet tell if there are more questions for the FAE team because of the published HEAD Documents.

The new decision here is whether we want to have a second HEAD document for a mainline release for now, as this allows a dual approach i.e. alternating mainline and NXP releases. And to make it really clear to customers, we could call it `HEAD_MAINLINE` or so instead of `PD24.1.y` unless officially released. We could  move to branches anytime, once we see support traffic going up.

If you find this too risky and expect many questions for unreleased BSPs, we should probably hide all HEAD documents in branches.

2024-02-06 09:02 UTC, ymoog commented
> If you find this too risky and expect many questions for unreleased BSPs, we should probably hide all HEAD documents in branches.

I renamed the pd24.1.y file, but kept the doc-id for now (since we also have the PD24.1.y manifest).

2024-02-06 09:12 UTC, jremmert-phytec-iot approved these changes
In Addition we could add a disclaimer note to all `HEAD` documents.

But we can do this in another PR.

EDIT: Let's wait with merging until @BHahn42618 approved, esp. regarding the FAE point.

2024-02-06 09:13 UTC, tremmet approved these changes

2024-02-06 10:42 UTC, tremmet approved these changes

2024-02-06 12:04 UTC, BHahn42618 approved these changes

2024-02-06 13:24 UTC, merged