static: change teal color to darker Phytec color
phytec/doc-bsp-yocto pull request #149
Opened 2024-02-01 14:22 UTC by jremmert-phytec-iot

The darker color is already used by the documentation of modules developed in US. In addition it looks more elegant. This commit adapts the color scheme (logo background and chapter-headings).

The Chapter-Headings in HTML are not very ergonomic in terms of contrast, but there is no useful information in them anyway (Contents, Contribute) and the immediate focus falls on the headings (Yocto Reference Manuals, i.MX 8 Manuals).

Reference US Modules:
https://docs.phytec.com/latest/phycore-am62x/developingwithyocto/index.html

Old:
![image](https://github.com/phytec/doc-bsp-yocto/assets/9881210/5a94b622-e8b2-4c8b-aeab-c7af87259179)

New:
![image](https://github.com/phytec/doc-bsp-yocto/assets/9881210/dff1318b-3917-4ced-bd21-edf5d3f4ff03)

2024-02-01 14:50 UTC, mschwan-phytec requested changes

2024-02-01 14:50 UTC, mschwan-phytec commented on source/sphinx/static/css/phytec-theme.css
> +    --phyteal: #006065;
This is not ideal, as `--phyteal` does not fit in the existing color scheme, regarding its name.

Additionally, I would like to keep this theme the same as used on our website, so the branding is consistent.

I am open to style changes diverting from the default RTD theme, but they should follow the look of our website's colors and styling, if possible.

2024-02-01 15:38 UTC, jremmert-phytec-iot commented on source/sphinx/static/css/phytec-theme.css
> +    --phyteal: #006065;
Right, I agree. The closest match would be `teal4` instsead of `teal3`. I updated the description above.

2024-02-02 08:14 UTC, mschwan-phytec approved these changes

2024-02-02 08:15 UTC, merged