Wip/andrej.picej@norik.com/bsp imx93
phytec/doc-bsp-yocto pull request #154
Opened 2024-02-16 09:40 UTC by andrejpicej

Hi all,

this PR brings BSP docs for i.MX93 PD24.1.0 release. We based everything on the i.MX8MP release and edited/added what was needed.

Reviewers should note that some solutions are dirty and should be dealt with on a general level to make them consistent and
easier for the next platform to be added in. I know...there is a lot of duplicated text!

Why we choose this "quick and dirty" solution:
It was the fastest way and we are in a hurry + didn't want to break something with i.MX8M docs.

While at it I wrote down some ideas on how the stuff can be organized so it is easier for the next platform/release:

```
netboot.rsti
 - whole or part of it can be made as a general file.

dt-overlays.rsti
 - whole or part of it can be made as a general file (imx specific maybe)?

standalone_build.rsti
 - whole or part of it can be made as a general file (imx specific maybe)?

format_sd-card.rsti
 - whole or part of it can be made as a general file (imx specific maybe)?

Peripherals in general:
 - should they follow alphabetical order?
Pin-Muxing
 - whole or part of the pin-muxing.rsti can be made as a general file (imx specific maybe)?
Network:
 - network.rsti can be made as a general file (PHYTEC specific?)
SD-Card:
 - sd-card.rsti can be made as a general file (PHYTEC specific?)
eMMC:
 - platform/emmc.rsti can also be made as a general file (PHYTEC or imx specific?)
I2C:
 - whole or part of it can be made as a general file (imx specific maybe)?
RTC:
 - names of RTC? should we change for every board so they match?
 - one-minute resolution note, only for imx8m
CANFD:
 - canfd can be put into general/imx peripherals
AUDIO:
 - PEB-AV-10 is mentioned in audio.rsti (general file), which is not supported by every PHYTEC board!
 - audio.rsti (general file) mentions TLV320 as audio codec. Some boards might use different audio codecs.
 - capture topic mentioned enabling mixers (no need by default) audio capture should be working by default.
VIDEO:
 - We don't have vpudec available, but is mentioned in the general video.rsti
 - Should only contain basic commands
 - bsp/$PLATFORM/peripherals/display.rsti can be made as a general include file
```

Of course, everything here is debatable since we don't want to spend too much time on this, but in the long run, it might be a good idea
to sort some of this stuff out. I guess maintainers and people working with these docs have a better overview of what should/could be done.

One thing I did (also edited i.MX8M docs) was to use the substitution for SD-Card and eMMC devs. They are now specified in imx9.rsti and imx8.rsti which are included in release.rst files.

I created a bunch of smaller commits so if it is easier for you to review I can also squash them together (please comment if this is the case).

2024-02-16 12:18 UTC, andrejpicej commented
Reduced the size of added images below 300M. Now the CI shouldn't have problems :).

2024-02-17 18:42 UTC, jremmert-phytec-iot commented
@andrejpicej thank you for the PR!

I am currently on leave and can only review it from 1. of March earliest unfortunately. I would like to review it, but my review would probably come too late as you want to have a first imx93 doc online soon.

Maybe @mschwan-phytec or @ymoog have time for a review earlier?

2024-02-19 12:27 UTC, BHahn42618 commented
Remember to squash some of the commits. See the note in the commit message of this commit:
`Applied further adaptions for the i.MX 93 on the BSP manual`.

2024-02-19 12:28 UTC, BHahn42618 requested changes

2024-02-19 12:28 UTC, BHahn42618 commented on source/bsp/imx9/peripherals/i2c-bus.rsti
> +I²C Bus
This file is identical to imx8/peripherals/i2c-bus.rsti. Move to => bsp/peripherals/i2c-bus.rsti and use for imx8 and imx9?
Note: Remember to update all the includes

2024-02-19 12:28 UTC, BHahn42618 commented on source/bsp/imx9/peripherals/network.rsti
> +``meta-ampliphy/recipes-core/systemd/systemd-conf``.
Also this file could be generalized and used for imx8 and imx9 with some minor changes => move to bsp/peripherals and modify the includes.

The meta-ampilphy path is also correct for imx8 (error in the imx8 documentation). meta-yogurt is old and not in any imx8 bsp anymore it got renamed to meta-ampliphy a while ago.

Maybe change the `|segin-sbc-network|` substitution (see line 19 of this file) and the `|pollux-sbc-network|` substitution from all the imx8 manuals to `|sbc-network|`.
The |pollux-sbc-network| substitution is also defined in imx8mm and imx8mn manuals (is just empty there), but that does not make much sence, because the imx8mn and imx8mm run on polis base-board not on pollux base-board.

2024-02-19 12:28 UTC, BHahn42618 commented on source/bsp/imx9/peripherals/pin-muxing.rsti
> +|soc| Pin Muxing
Also this file is identical to imx8 documentation. No need to use two files. Move bsp/imx8/peripherals/pin-muxing.rsti to /bsp/peripherals/pin-muxing.rsti and include the file in imx8 and imx9 manuals.
Note: Remember to modify all the includes in the imx8 manuals.

2024-02-19 12:28 UTC, BHahn42618 commented on source/bsp/imx9/peripherals/sd-card.rsti
> +SD/MMC Card
Also this file is identical to imx8 documentation. No need to use two files. Move bsp/imx8/peripherals/pin-muxing.rsti to /bsp/peripherals/pin-muxing.rsti and include the file in imx8 and imx9 manuals.
Note: Remember to modify all the includes in the imx8 manuals.

2024-02-20 06:57 UTC, andrejpicej commented on source/bsp/imx8/imx8.rsti
> +.. imx8 specific substitutions
I went with this solution because it looked like a good idea at the time. Basically my idea was to use this file for any platfrom/soc-specific substitutions, so we don't have the same duplicates in manuals. I think I though that there will be more of these substitutions, but looking into it I guess there are not many more. So we can get rid of them if you think it makes more sense.

2024-02-20 06:57 UTC, andrejpicej commented on source/bsp/imx9/imx93/imx8mp.rst___NEW
> +====================
Probably left behind after the initial copy. Missed it. Will be removed. Thanks.

2024-02-20 07:15 UTC, andrejpicej commented on source/bsp/getting-started.rsti
> +      host:~$ zstdcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
Used this to test it:
`host$ zstdcat phytec-qt6demo-image-phyboard-segin-imx93-2.wic.xz | sudo dd of=/dev/sdd bs=1M conv=fsync status=progress`
Works just fine :)
Why I went with zstdcat was because Christoph suggested it and I didn't give it much thought.
Nevertheless, I can change it to unxz if you think it makes more sense :).

2024-02-20 07:23 UTC, andrejpicej commented on source/bsp/imx9/development/format_sd-card.rsti
> +Format SD-Card
I would do things like this later if you are ok with it. Don't want to spend much time on refactoring right now. Maybe I can create an issue so we don't forget it.

2024-02-20 07:23 UTC, andrejpicej commented on source/bsp/imx9/peripherals/display.rsti
> +Backlight Control
Agreed that this can be done, but don't know if we want to do that now. Maybe I fix other things first and then come back to this.

2024-02-20 07:36 UTC, andrejpicej commented on source/bsp/imx9/development/uuu.rsti
> +   host:~$ sudo uuu imx-boot
It does work, but in that case the uuu tool doesn't return. We have to manually exit with CTRL+C. That's why I used the option without `-b spl`. Do you experience the same behaviour?

2024-02-20 07:39 UTC, andrejpicej commented on source/bsp/imx9/development/uuu.rsti
> +      u-boot=> mmc partconf 0 0 0 0
Agreed, like many other files this could also be generalized. Maybe we can do that in a separate PR?

2024-02-20 07:41 UTC, andrejpicej commented on source/bsp/imx9/peripherals/network.rsti
> +``meta-ampliphy/recipes-core/systemd/systemd-conf``.
Ok, like similar comment before, maybe this can be done in a separate PR?

2024-02-20 07:41 UTC, andrejpicej commented on source/bsp/imx9/peripherals/pin-muxing.rsti
> +|soc| Pin Muxing
Seperate PR maybe?

2024-02-20 07:41 UTC, andrejpicej commented on source/bsp/imx9/peripherals/sd-card.rsti
> +SD/MMC Card
Seperate PR maybe?

2024-02-20 07:47 UTC, andrejpicej commented
@BHahn42618 Thank you very much for your review. I will start working on the proposed changes.
I guess you also noticed some files could be generalized and made available for both i.MX8 and i.MX9 boards. We will align today on how urgent it is to make this i.MX93 BSP manual available as soon as possible and decide if maybe the refactoring and using generalized files should be done here or maybe later in a separate PR.
Thanks for your review :).

2024-02-20 09:05 UTC, andrejpicej commented on source/bsp/imx9/development/format_sd-card.rsti
> +Format SD-Card
Looking into this I will also move all the gparted images into the base source/bsp/images folder so we don't have that duplicated :)

2024-02-20 10:54 UTC, andrejpicej commented
Fixed what was pointed to by the @BHahn42618 in the i.MX93 specific files. I didn't touch the generalization of the files though. @cstoidner will do that and create a new PR, that's why I marked this as a draft.

2024-02-20 11:45 UTC, BHahn42618 commented on source/bsp/imx9/development/uuu.rsti
> +   host:~$ sudo uuu imx-boot
Yes, I can see that behaviour on imx8 too.

2024-02-27 08:40 UTC, cstoidner commented
Further work on this PR happens here: https://github.com/phytec/doc-bsp-yocto/pull/156

2024-03-04 08:24 UTC, jonas-rem commented
Closed in favor of #156. Please re-open if needed.

2024-03-04 08:24 UTC, closed without merging