bsp: imx8: installing-os: rework flash SPI NOR from SD-Card chapter
phytec/doc-bsp-yocto pull request #155
Opened 2024-02-19 10:35 UTC by BHahn42618

correct small mistake in mount command for sd-card. add comment that the fspi image needs to be copied to SD-Card also to the other chapter.

depends on #154

2024-02-19 10:44 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +   imx-boot-|yocto-machinename|-fspi.bin-flash_evk_flexspi to the first partition
I think you should not drop the information that this is the vfat partition. Maybe add this information into parentheses. Or is there any other reason why you removed it?

2024-02-19 11:38 UTC, BHahn42618 commented on source/bsp/imx8/installing-os.rsti
> +   imx-boot-|yocto-machinename|-fspi.bin-flash_evk_flexspi to the first partition
Theoretically you could also boot from eMMC and insert an SD-Card with just one partition, that does not need to be FAT, but could also be ext4. For the command below/ chapter to work it just needs to be the first partition on the sdcard. That is why I dropped it.

2024-02-19 11:46 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +   imx-boot-|yocto-machinename|-fspi.bin-flash_evk_flexspi to the first partition
Okay, thanks.

2024-02-19 11:48 UTC, tremmet approved these changes

2024-02-26 08:03 UTC, ymoog approved these changes

2024-03-07 17:17 UTC, jonas-rem commented
@BHahn42618 can you please rebase on the current master. The linkcheck action should be ok after a rebase.

2024-03-11 09:20 UTC, BHahn42618 commented
Rebased to main. Linkcheck still fails because imx93 manual contains a broken link (see #160). Added a second commit that will create the sdcarddev substitution and use the sdcard peripheral documentation from imx-common.

2024-03-11 10:13 UTC, jonas-rem requested changes

2024-03-11 10:29 UTC, BHahn42618 commented
Rebase to main after #160 got merged, Linkcheck passes now.

2024-03-11 11:47 UTC, tremmet commented on source/bsp/imx8/imx8mm/head.rst
> +.. |sdcarddev| replace:: mmcblk1
For i.MX95 the SD interface will be (by now) uSDCH2. As the numbering starts with 1 in HW this will likely lead to mmcblk1 in SW. 
So if nothing changes the SD-Card interface will be the same for i.MX95 and i.MX8M*. Only the eMMC will be 0 instead of 2.

2024-03-12 13:34 UTC, jonas-rem approved these changes

2024-03-12 13:35 UTC, merged