bsp: Introduce bsp manual for i.MX 93
phytec/doc-bsp-yocto pull request #156
Opened 2024-02-26 21:53 UTC by cstoidner

This PR introduces the BSP manual for the i.MX 93.

That is accomplished with the two steps below:

**Step 1:**
Copy files from `bsp/imx8/` and `bsp/imx8/imx8mp/` as templates to a new folder `bsp/imx93/`, and adapt them for purpose of i.MX 93. Whenever justifiable from "i.MX 93" work-scope, apply adaptions in a general manner (e.g. with reST substitutions), to encourage re-use across various i.MX platforms.

**Step 2:**
Move files that could be used across various i.MX platforms to a new folder `bsp/imx-common`, and potentially apply further generalization.

--

After that PR was merged i.MX 8 platform can also make use of the "imx-common" files, can add further generalization as needed, and can drop their local duplicates from `imx8/*` folders.

--

That PR is a continuation of PR https://github.com/phytec/doc-bsp-yocto/pull/154
All commits of PR #154 are here contained, but squashed in the two existing commits. Also correction and a few improvements of wording and format are contained.

2024-02-26 21:54 UTC, cstoidner commented
Please note:
That PR is currently in draft mode, as there are some adaptions not finally yet complete. Especially documents concerning "peripherals" are not yet finalized. That includes files:
* `source/bsp/peripherals/audio.rsti`
* `source/bsp/peripherals/emmc.rsti`
* `source/bsp/peripherals/rtc.rsti`
* `source/bsp/imx9/peripherals/*`

Also, some more files might be added to `bsp/imx-common`.

2024-02-27 08:08 UTC, andrejpicej requested changes
Thanks, looks better and more organized :). Some comments and suggestions though :).

2024-02-27 08:08 UTC, andrejpicej commented on source/bsp/imx9/peripherals/pin-muxing.rsti
Identical to the i.MX8 one, can probably be moved to a common place.

2024-02-27 08:08 UTC, andrejpicej commented on source/bsp/imx9/peripherals/pxp.rsti
> +GStreamer and Wayland` (AN13829) Application note from NXP.
\ No newline at end of file. Again my fault. Sorry :smiling_face_with_tear:

2024-02-27 08:08 UTC, andrejpicej commented on source/bsp/imx9/peripherals/sd-card.rsti
Can probably be moved to a common place, since the only difference is using the substitutions.

2024-02-28 07:35 UTC, ymoog requested changes
What about naming the imx directory ``imx`` instead of ``imx-common``. This would be consistent with other dir naming. e.g. we have a ``bsp`` dir not a ``bsp-common`` dir.

I agree with Andrej, we can do better with regards to creating common flies.

dt-overlay file for example could be structured in a way that first all the common operations that can be done with overlays are explained. And after that we explain the soc specific overlays (in a different soc specific file).
Maybe also for gpio, led and tm?

2024-02-28 07:35 UTC, ymoog commented on source/bsp/imx9/peripherals/pm.rsti
> +Unlike i.MX8 M family the i.MX 93 doesn't support *Dynamic* Voltage and
This file is in the imx9 directory, but you speak of the i.MX 93. It should probably be moved to the imx93 directory, then.

2024-02-28 07:35 UTC, ymoog commented on source/bsp/imx9/peripherals/canfd.rsti
Afaik the imx93 uses the same flexcan driver as imx8mp so we can probably make this file generic?

2024-02-28 07:35 UTC, ymoog commented on source/bsp/imx9/peripherals/display.rsti
Let's make this generic as well. We can restructure imx8 if necessary.

2024-02-28 07:35 UTC, ymoog commented on source/bsp/imx9/peripherals/eeprom.rsti
> +   Data in the first 265 bytes of the normal EEPROM area (bus: I2C-0 addr: 0x51)
```suggestion
   Data in the first 265 bytes of the normal EEPROM area (bus: I2C-2 addr: 0x50)
```

2024-02-28 07:35 UTC, ymoog commented on source/bsp/imx9/peripherals/eeprom.rsti
> +about the module in the early stage.
I hope you do not have any SoM with EEPROM API < 2. I assume you can omit this paragraph?!

2024-03-01 17:17 UTC, cstoidner commented on source/bsp/getting-started.rsti
> +   host:~$ zstdcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
Sorry, I actually missed that discussion in the first PR. Sorry @BHahn42618  !
Let me address this here, I will link then that discussion from here into the first PR. 

Let me refer/response to the points from @BHahn42618  in the first PR (#154)

> in the documentation it says zstdcat is for compressing
> or uncompressing .zst files not .xz. Can this really be
> used for .xz files also?

That is indeed a good point. Looking into the man-pages one might assume the option `--format=xz` must be used to tell `zstdcat` that "xz"-algorithm shall be used. I used zstdcat for years and it works great, also for "xz" without any `--format` argument. Maybe it detects xz-algorithm due to the "xz" suffix of the file... However thats just an
assumption and might not work for all implementations of zstdcat (as it is not specified in the man-page). So thats a fair argument we need to consider.

> I would also expect a -d here for decompression, as it
> says default is compression.

Please be aware, we use `zstdcat`, not `zstd`. As you can see in the man-page `zstdcat` is queal `zstd -dcf`. That means it does always decompress (-d) and write to stdout (-c)

---

Apart from those details, I definitely perefer a method that pipes on the fly into `dd`, and avoids to create a physical file to uncompress the image. One advantage of that is you dont have to worry about a location to store that uncompressed file, that you will anyway delete immediately again after calling `dd`.

And especially when you use a `wic.xz` file from some public build location (e.g. a nightly build-pipeline, or an official release-folder, in our case `~/share/sw_data/Software/BSP-Yocto-*/**/`), the pipe-approach avoids hassles you might have:

- you have (hopefully) no write access to those public folders, so you have to think where to put the uncompressed file locally, and remove it again afterwards 
- or even critical: you have write-access to those public folder, then unxz's default behaviour is to remove the compressed xz-file and place the uncompressed version instead into that folder; 

To make it short, I feel the best solution is to use `xzcat` instead of `zstdcat` or `unxz`:
  - `xzcat` definitely uses the 'xz' algorithm
  - `xzcat` writes to stdout and so allows to pipe

That means:
  `host:~$ xzcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress`

2024-03-01 17:21 UTC, cstoidner commented on source/bsp/getting-started.rsti
> +   host:~$ zstdcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
> We have a section in the manual about bmaptools. We should use that instead of dd for compressed/wic images.

@ymoog , we have not much changed here, compared to i.MX 8 manuals. Beside partup and bmaptools, `dd` is just the 3rd option to flash an image (thats the same in the i.MX 8 Manuals). Only difference here: Our `*.wic` is compressed, so it need to be uncompressed before giving to `dd`.

2024-03-01 17:32 UTC, cstoidner commented on source/bsp/imx-common/development/format_sd-card.rsti
To keep it simple I would first like to put all equal things from imx8 and imx9 into the imx-common folder. Later we can decide to move individual things from imx-common even one level higher, if they are not imx specific.

I hope that's a good balance between speeding up the review/acceptance of that PR, by having also a good and future-proof structure.

2024-03-01 17:47 UTC, cstoidner commented on source/bsp/imx-common/development/netboot.rsti
Same as for the comment https://github.com/phytec/doc-bsp-yocto/pull/156#discussion_r1509312884 above.

2024-03-01 17:48 UTC, cstoidner commented on source/bsp/imx-common/development/standalone_build.rsti
I agree. So same as for the comment https://github.com/phytec/doc-bsp-yocto/pull/156#discussion_r1509312884 above.

2024-03-01 18:12 UTC, cstoidner commented on source/bsp/imx-common/development/format_sd-card.rsti
> +.. image:: /bsp/imx8/images/gparted1.png
True. Solved now, see commit  d28d9adc20978f2d66b12fdd3d841985b1c190fb

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-01 18:19 UTC, cstoidner commented on source/bsp/imx9/images/gparted1.png
True. Solved now, see commit  291cb578c2aff8487e84dc29571547838d7cdf56

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-01 18:55 UTC, cstoidner commented on source/bsp/imx-common/development/uuu.rsti
> +      u-boot=> mmc partconf 0 0 0 0
True. Solved now, see commit  e70d22b82c519c28fd4f4de2e3e6369ee07b6991

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-01 19:33 UTC, cstoidner commented on source/bsp/imx9/peripherals/eeprom.rsti
> +   Data in the first 265 bytes of the normal EEPROM area (bus: I2C-0 addr: 0x51)
Thanks for pointing out. Fixed in d1aa3a8f0a46e55ecdee6404781760eb3a251799

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-01 19:35 UTC, cstoidner commented on source/bsp/imx9/imx93/pd24.1.0.rst
> +	:end-before: .. audio_alsa_configuration_start_label
Solved now, see commit  a24694f72fd562f8df3c2c35687d8dab4080f17d

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-04 08:17 UTC, BHahn42618 commented on source/bsp/getting-started.rsti
> +   host:~$ zstdcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
@cstoidner I agree with you piping it directly into `dd` is a useful feature. Your suggestion with `xzcat` looks fine to me.

2024-03-04 16:09 UTC, cstoidner commented on source/bsp/imx9/imx93/display.rsti
> +``BOOT/bootenv.txt`` by default!
Fixed now, see commit  9b70aaa2535c75f916f047ad81e3343c35e1fc63

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-04 16:10 UTC, cstoidner commented on source/bsp/imx9/peripherals/ocotp-ctrl.rsti
> +   target:~$ hexdump /sys/devices/platform/soc\@0/47510000.efuse/fsb_s400_fuse0/nvmem
Fixed now, see commit  9b70aaa2535c75f916f047ad81e3343c35e1fc63

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-04 16:10 UTC, cstoidner commented on source/bsp/imx9/peripherals/pxp.rsti
> +GStreamer and Wayland` (AN13829) Application note from NXP.
Fixed now, see commit  9b70aaa2535c75f916f047ad81e3343c35e1fc63

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-04 17:12 UTC, cstoidner commented on source/bsp/imx9/imx93/emmc.rsti
I agree. Done now with commit  2f010ce58f1ccfd09bfa7f0a8b601ddc06d4d03a

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-04 17:32 UTC, cstoidner commented on source/bsp/imx9/peripherals/pin-muxing.rsti
I agree. Done now with commit  3bbf078b87ed5d7663dbf0f31d1b084abdd47c17

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-04 17:32 UTC, cstoidner commented on source/bsp/imx9/peripherals/sd-card.rsti
I agree. Done now with commit  3bbf078b87ed5d7663dbf0f31d1b084abdd47c17

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-04 18:02 UTC, cstoidner commented on source/bsp/imx9/peripherals/network.rsti
I agree. Done with commit 77f2baaed5abf076718cc48ab16634119f551e6a

NOTE: Before merging that PR, I will squash that commit into 0e779ccd795f9f68cefefc699fddb3a495b2f8e7

2024-03-04 18:12 UTC, cstoidner commented on source/bsp/imx9/imx93/pd24.1.0.rst
> +.. IMX8(MP) specific
Fixed, see 3580193e60915f1da16fea3f939a8e7d80668dcc

NOTE: Before merging that PR, I will squash that commit into f6bde8c6bf9ad168986059021f619c3c15336920

2024-03-04 18:17 UTC, cstoidner commented on source/bsp/imx9/installing-os.rsti
There are a few differences to `source/bsp/imx8/installing-os.rsti` that need to be considered to make it a common file. We should work together with i.MX 8 Team on it, when that i.MX 93 specific PR was done.

2024-03-04 18:22 UTC, cstoidner commented on source/bsp/imx9/peripherals/canfd.rsti
I dont think it is the same driver. The imx93 has flexcan, and imx8mp seems to use "mcp25xxfd". So lets go for now with a platform specific document. 

When that i.MX 93 specific PR was done, we both should check together if it makes sense establish here a common document.

2024-03-04 18:25 UTC, cstoidner commented on source/bsp/imx9/peripherals/display.rsti
Most of that document is speaking about backlight/brightness, which differs in imx8 and imx9. Lets go here for now with a platform specific document.

And again, when that i.MX 93 specific PR was done, we both should check together if it makes sense establish here a common document.

2024-03-05 09:01 UTC, andrejpicej approved these changes
Looks good to me. Like you wrote @cstoidner  there is still some generalization to be done. If i.MX8 team is OK with the current state this can then be done in separate PRs.

2024-03-05 10:38 UTC, BHahn42618 requested changes

2024-03-05 10:38 UTC, BHahn42618 commented on source/bsp/imx-common/development/netboot.rsti
> +   overlays=imx93-phyboard-segin-peb-av-02.dtbo imx93-phyboard-segin-peb-eval-01.dtbo
Not really common these names. Please use at least the already existing `|dt-carrierboard|` substitution instead of hardcoding `imx93-phyboard-segin`. Maybe also create a substitution for the `peb-av-02`. This would make it easier to include the file for the imx8 later on.

2024-03-06 12:21 UTC, cstoidner commented on source/bsp/imx-common/development/netboot.rsti
> +   overlays=imx93-phyboard-segin-peb-av-02.dtbo imx93-phyboard-segin-peb-eval-01.dtbo
> Maybe also create a substitution for the peb-av-02. This would make it easier to include the file for the imx8 later on.

Not all platforms necessarily offer a `peb-av-02` overlay, as there is not standard set of DTBOs for all platforms. That makes it hard to follow your wish with substitutions here. Finally it is just a simple example that shows where/how to place the space characters between file-names.

I have now replaced both overlay file names with generic example file names `example-overlay1.dtbo` and `example-overlay2.dtbo`. I think that serves its purpose and avoids unnecessary complications.

See a15c8190ed8634712cd8610fea9cb3c31b65e18c

2024-03-06 13:49 UTC, cstoidner commented on source/bsp/imx9/peripherals/eeprom.rsti
> +about the module in the early stage.
Removed that sentence as we have only APIv2. See e4c3bdfc6ec5486e5d50f9a29406d88da5e74742

2024-03-06 13:56 UTC, cstoidner commented on source/bsp/getting-started.rsti
> +   host:~$ zstdcat |yocto-imagename|-|yocto-machinename|.wic.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
Now `zstdcat` was replaced with `xzcat`, see 22f5386c40e826185d0ad4fd57c281e8d0e4b6e2

2024-03-06 14:06 UTC, cstoidner commented on source/bsp/imx9/peripherals/pm.rsti
> +Unlike i.MX8 M family the i.MX 93 doesn't support *Dynamic* Voltage and
File was now moved. See db8a0eae7c60d274b6485498c135a4950fcdc2f3

2024-03-07 07:17 UTC, ymoog approved these changes

2024-03-07 08:16 UTC, pfiser approved these changes

2024-03-07 11:13 UTC, jonas-rem commented
@cstoidner is this PR ready to merge? If yes, can you click "Ready for review".

@BHahn42618 are you ok with the most recent changes? You had some remarks earlier.

If everything is good to go I will merge it later.

2024-03-07 14:03 UTC, andrejpicej approved these changes

2024-03-07 15:29 UTC, cstoidner commented
> If everything is good to go I will merge it later.

It is now in "ready for review", and for me its even ready to be merged.
@jonas-rem , would you do a squash-mege? All the small fixing commits were useful for the review, but will be confusing in the commit-history of the official branch.

2024-03-07 17:07 UTC, merged