Wip/bhahn/bspimx8 m 3179: cleanup mainline head for release
phytec/doc-bsp-yocto pull request #162
Opened 2024-03-25 10:23 UTC by BHahn42618

remove chapters about unsupported features:
- no SPI NOR Flash support in U-Boot
- no suspend to RAM support
- no support for EEPROM ID-Page
- no support for audio

2024-03-25 10:58 UTC, tremmet requested changes

2024-03-25 10:58 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   but usually (in other releases) it will also be used for board detection.
The ID page **is** used for board detection. See: https://github.com/phytec/u-boot-phytec/blob/30ed1d3bc40f724af68e83a027e357af657bdd0d/board/phytec/phycore_imx8mp/spl.c#L29 The only thing is that you can not read write the data with a EEPROM driver in U-Boot and kernel as the device is not included in the device tree. So you should rephrase this a little bit.

2024-03-25 14:38 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   but usually (in other releases) it will also be used for board detection.
Ok, done.

2024-03-26 07:38 UTC, ymoog commented
@BHahn42618 What is the goal of this PR? Please explain that in the PR summary comment.

2024-04-02 08:56 UTC, ymoog submitted a review, later dismissed

2024-04-02 12:10 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +      u-boot=> tftp ${loadaddr} |yocto-imagename|-|yocto-machinename|.wic
when using dynamic ips. Do we need to use the dhcp instead of tftp?

2024-04-04 12:02 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +      u-boot=> tftp ${loadaddr} |yocto-imagename|-|yocto-machinename|.wic
Yes. Done.

2024-04-09 08:22 UTC, ymoog approved these changes

2024-04-09 08:22 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +      u-boot=> dhcp ${loadaddr} |yocto-imagename|-|yocto-machinename|.wic
${loadaddr} is not necessary.

2024-04-09 11:34 UTC, tremmet approved these changes

2024-04-10 11:32 UTC, tremmet approved these changes

2024-04-15 11:46 UTC, merged