Wip/bhahn/BSPIMX8M-3195: include chapters from imx-common in imx8 manuals
phytec/doc-bsp-yocto pull request #163
Opened 2024-03-25 14:26 UTC by BHahn42618

include the following chapters from imx-common:
- source/bsp/imx-common/development/format_sd-card.rsti
- source/bsp/imx-common/development/uuu.rsti
- source/bsp/imx-common/development/netboot.rsti
- source/bsp/imx-common/peripherals/i2c-bus.rsti
- source/bsp/imx-common/peripherals/network.rsti
- source/bsp/imx-common/peripherals/pin-muxing.rsti
- source/bsp/imx-common/emmc.rsti

Generalize source/bsp/imx9/peripherals/display.rsti move to imx-common and include in imx8 and imx9 @cstoidner 

Do not include bsp/imx-common/development/standalone_build.rsti, because bigger changes are needed before this can be included in imx8.

2024-03-26 07:34 UTC, ymoog requested changes

2024-03-26 07:34 UTC, ymoog commented on source/bsp/imx8/imx8mm/head.rst
> +.. |ref-disable-emmc-part| replace:: :ref:`Disable booting from eMMC boot partitions <emmc-disable-boot-part>`
This substitution is used in the uuu chapter and has nothing to do with the emmc.rsti you (want) to modify here. Maybe happend accidentally when rebasing? You did not introduce an u-boot-offset as you said you do in your commit message.

2024-03-26 07:34 UTC, ymoog commented on source/bsp/imx8/imx8mm/head.rst
> +.. |sbc-network| replace:: \
Why can you change that all of a sudden? Please provide an explanation in your commit message.

2024-03-26 07:56 UTC, BHahn42618 commented on source/bsp/imx8/imx8mm/head.rst
> +.. |ref-disable-emmc-part| replace:: :ref:`Disable booting from eMMC boot partitions <emmc-disable-boot-part>`
The `emmc-disable-boot-part` marker is introduced in emmc.rsti, so I created the substitution for this marker here, but you are correct, the substitution is used in uuu.rsti the first time (which gets included in the next commit). If you want I can move the Introduction of the substitution to the uuu commit.

I never said, that I would introduce an u-boot-offset substitution. I said I would use it and I did just that. I replaced the hardcoded 32kiB in emmc.rsti with the u-boot-offset substitution. The substitution already exists in our manual there is no need to introduce it. I can just use it.

2024-03-26 08:40 UTC, BHahn42618 commented on source/bsp/imx8/imx8mm/head.rst
> +.. |sbc-network| replace:: \
Done. Hope this is okay now.

2024-03-26 12:23 UTC, ymoog commented on source/bsp/imx8/imx8mm/head.rst
> +.. |ref-disable-emmc-part| replace:: :ref:`Disable booting from eMMC boot partitions <emmc-disable-boot-part>`
> The `emmc-disable-boot-part` marker is introduced in emmc.rsti, so I created the substitution for this marker here, but you are correct, the substitution is used in uuu.rsti the first time (which gets included in the next commit). If you want I can move the Introduction of the substitution to the uuu commit.

Yes, please.

> 
> I never said, that I would introduce an `|u-boot-offset|` substitution. I said I would use it and I did just that. I replaced the hardcoded 32kiB in emmc.rsti with the u-boot-offset substitution. The substitution already exists in our manual there is no need to introduce it. I can just use it.

Ah, makes sense. Thanks.

2024-03-27 14:53 UTC, BHahn42618 commented on source/bsp/imx8/imx8mm/head.rst
> +.. |ref-disable-emmc-part| replace:: :ref:`Disable booting from eMMC boot partitions <emmc-disable-boot-part>`
Ok moved the introduction of the emmc-disable-boot-part marker to the uuu commit.

2024-04-02 05:53 UTC, ymoog approved these changes

2024-04-02 12:22 UTC, tremmet approved these changes

2024-04-02 15:07 UTC, jonas-rem commented
@BHahn42618 is this PR ready for merging? If so, you can set it to "Ready for review" and I will merge it later.

2024-04-03 08:06 UTC, merged