BSPIMX8M-3185 Rework the network setup and network boot section to support DHCP
phytec/doc-bsp-yocto pull request #164
Opened 2024-03-26 09:40 UTC by ymoog

The goal is to create, in order of priority:

1. A correct BSP manual for the imx8mp mainline BSP
2. A unified manual for mainline and nxp BSPs
3. A shared/common imx manual.

2024-03-26 11:00 UTC, BHahn42618 commented
Interesting. You have a much more complicated TFTP server setup. For the internal and external Tests I have done a tftp server setup on my system too. This is what my setup looks like:
`/etc/dhcp/dhcpd.conf`
```
subnet 192.168.3.0 netmask 255.255.255.0 {
range 192.168.3.11 192.168.3.250;
option broadcast-address 192.168.3.255;
option routers 192.168.3.10;
}
```
`/etc/default/isc-dhcp-server`
```
INTERFACESv4="enp53s0"
INTERFACESv6=""
```
Are your extra options really needed? Is it working without modifying the `/etc/default/isc-dhcp-server` file? Why did you choose 255.255.255.224 as a netmask and 192.168.3.31 as a broadcast address? Is that working, because on the device the ethernet interfaces are configured for netmask 255.255.255.0 and broadcast address would then be 192.168.3.255. I don't know if this could maybe cause conflicts.

2024-03-26 12:12 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   sample:
@BHahn42618 I wrote here that the internal subnet example is being used. I modified as little as necessary.

2024-03-26 12:14 UTC, ymoog commented
>  Is that working, because on the device the ethernet interfaces are configured for netmask 255.255.255.0 and broadcast address would then be 192.168.3.255. I don't know if this could maybe cause conflicts.

The ethernet interfaces should be configured according to dhcp.
See an excerpt of the kernel log:
```
[    6.517340] IP-Config: Got DHCP answer from 192.168.3.10, my address is 192.168.3.17
[    6.525105] IP-Config: Complete:
[    6.528343]      device=eth0, hwaddr=50:2d:f4:3a:3b:e2, ipaddr=192.168.3.17, mask=255.255.255.224, gw=192.168.3.1
[    6.538616]      host=192.168.3.17, domain=internal.imx8.devboard, nis-domain=(none)
[    6.546366]      bootserver=192.168.3.10, rootserver=192.168.3.10, rootpath=
[    6.546374]      nameserver0=192.168.3.10
```

2024-03-26 12:34 UTC, tremmet commented
@ymoog I understand that you try to use an approach with minimal change. But I agree with Benjamin. We should align the DHCP configuration with the static ip settings in the BSP. And even more with the configuration for the tftp and nfs server.
They are also using a 255.255.255.0 netmask.
And 192.168.3.10 should be the router.

2024-03-26 12:42 UTC, ymoog commented
> @ymoog I understand that you try to use an approach with minimal change. But I agree with Benjamin. We should align the DHCP configuration with the static ip settings in the BSP. And even more with the configuration for the tftp and nfs server. They are also using a 255.255.255.0 netmask. And 192.168.3.10 should be the router.

Ok, I will change the netmask. However the router does not matter, only the server ip address, which is still the same as for TFTP and NFS; as can be seen in the log I provided. Thus, I would like to keep router address as is. What do you think?

2024-03-26 13:56 UTC, tremmet commented
> > @ymoog I understand that you try to use an approach with minimal change. But I agree with Benjamin. We should align the DHCP configuration with the static ip settings in the BSP. And even more with the configuration for the tftp and nfs server. They are also using a 255.255.255.0 netmask. And 192.168.3.10 should be the router.
> 
> Ok, I will change the netmask. However the router does not matter, only the server ip address, which is still the same as for TFTP and NFS; as can be seen in the log I provided. Thus, I would like to keep router address as is. What do you think?

Does does the router lead into `gw=192.168.3.1` ? I think the gateway of the target should be your host pc. Or where does this come from?

2024-03-27 07:23 UTC, ymoog commented
> > > @ymoog I understand that you try to use an approach with minimal change. But I agree with Benjamin. We should align the DHCP configuration with the static ip settings in the BSP. And even more with the configuration for the tftp and nfs server. They are also using a 255.255.255.0 netmask. And 192.168.3.10 should be the router.
> > 
> > 
> > Ok, I will change the netmask. However the router does not matter, only the server ip address, which is still the same as for TFTP and NFS; as can be seen in the log I provided. Thus, I would like to keep router address as is. What do you think?
> 
> Does does the router lead into `gw=192.168.3.1` ? I think the gateway of the target should be your host pc. Or where does this come from?

Yes. I don't believe there is such a thing as  a gateway of a physical device. However I am not sure if a gateway is needed. Maybe the gateway functionality is controlled via software on the host PC. So it acts as both a router and a client.

2024-03-27 13:26 UTC, BHahn42618 requested changes

2024-03-27 13:26 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +         host:~# service isc-dhcp-server restart
this did not work for me. I think the service has to be running for a restart. After the install the service was in status "failed" for me. Try this:
```suggestion
         host:~# sudo systemctl stop isc-dhcp-server
         host:~# sudo systemctl start isc-dhcp-server

2024-04-02 06:47 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +         host:~# service isc-dhcp-server restart
How about

```bash
service isc-dhcp-server --full-restart
```

2024-04-03 08:08 UTC, jonas-rem commented
@ymoog after merging #163, there are merge conflicts here. Can you rebase on the current main?

2024-04-04 19:45 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +         host:~# service isc-dhcp-server restart
Difficult to test if this works. I got the error only when installing the dhcp-server for the first time on the host machine. When uninstalling and reinstalling it this did not work. I think I got the error because the program went into some failed state after installing it for the first time.
But I would use :~$ instead of :~# and put a sudo into the command. I don't think  that we use the :~# style anywhere and I don't think anyone is gonna get that it means that you have sudo rights.

2024-04-05 08:58 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +         host:~# service isc-dhcp-server restart
> Difficult to test if this works. I got the error only when installing the dhcp-server for the first time on the host machine. When uninstalling and reinstalling it this did not work. I think I got the error because the program went into some failed state after installing it for the first time. 

That is why I suggested --full-restart. It does exactly what you suggested; in one command.

> But I would use :~$ instead of :~# and put a sudo into the command. I don't think that we use the :~# style anywhere and I don't think anyone is gonna get that it means that you have sudo rights.

The $ vs # is a standard convention since this is what your prompt looks like when you are root. But I can see that this is easily missed. I'll change it to ``~$ sudo``

2024-04-05 09:17 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   sample:
We should switch to [kea](https://ubuntu.com/server/docs/how-to-install-and-configure-isc-kea). I will take a look and modify the manual accordingly

2024-04-09 07:33 UTC, BHahn42618 commented on source/bsp/imx-common/development/host_network_setup.rsti
> +         host:~$ sudo systemctl restart kea-dhcp4-server
For this to work, the interface specified above needs to be active (on laptops there needs to be some device connected and powered on, so the interface does not turn off) and the interface needs to be configured to the static IP address 192.168.3.10 otherwise the dhcp server will fail. Maybe add a note for this. Otherwise it looks fine to me

2024-04-09 08:25 UTC, ymoog commented on source/bsp/imx-common/development/host_network_setup.rsti
> +         host:~$ sudo systemctl restart kea-dhcp4-server
Well yes. Why do you mention it now? This is the same for all the other imx8 manuals we have. Nothing changes here. The good thing is that you are alerted to the misconfiguration where before in the other imx8 manuals you would notice this mistake later. If you would like a note to this, we should put it somewhere else where we first mention a hardcoded ip address. Do you have a suggestion for a suitable location?

2024-04-09 11:10 UTC, tremmet requested changes

2024-04-09 11:17 UTC, ymoog commented on source/bsp/imx-common/development/host_network_setup.rsti
> +      }
Yes and no. I was not sure what to keep, so I used an example from the [doc](https://kb.isc.org/docs/kea-configuration-for-small-office-or-home-use) and reduced the content.

2024-04-09 11:50 UTC, ymoog commented on source/bsp/imx-common/development/host_network_setup.rsti
> +         host:~$ sudo systemctl restart kea-dhcp4-server
I see you mean that if the network interface is not present on (host) system startup then the dhcp server startup will fail and you have to restart it once you manually set up the network interface.

In that case, I will add a note that a specific order needs to be followed when working with dhcp. Thanks for pointing this out!

2024-04-09 13:02 UTC, tremmet approved these changes

2024-04-09 13:22 UTC, BHahn42618 approved these changes

2024-04-15 09:18 UTC, Varakala02 approved these changes

2024-04-15 11:40 UTC, merged