Wip/varakala02/bspimx8 m 3169 use yocto imageext substitution
phytec/doc-bsp-yocto pull request #170
Opened 2024-04-04 15:12 UTC by Varakala02

Hi,

Files that are generic and part of image extension are dissolved into the imx8mp mainline head and updated to use "rootfs.wic" image extension, as PD24.1.1 has different image extension than other BSP releases.

Preferred dissolving files than using more substitutes to make the documentation changes independent with other BSP documentations.

2024-04-09 11:36 UTC, Varakala02 commented
@cstoidner I request you also to review as I have updated with yocto-imageext-partup substitution variable in bsp imx93 documentaion. Thank you

2024-04-09 11:44 UTC, tremmet requested changes

2024-04-09 11:44 UTC, tremmet commented on source/bsp/getting-started.rsti
> +   host:~$ xzcat |yocto-imagename|-|yocto-machinename|.|yocto-imageext|.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
imx93 is already using wic.xz. So this will result in a wic.xz.xz

2024-04-09 11:44 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-imageext-partup| replace:: rootfs.partup
Anyone aware why we have the rootfs suffix here? Is it just because it is newer?

2024-04-10 06:19 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-imageext-partup| replace:: rootfs.partup
Have not investigated, yet. I assume upstream changed something?

2024-04-10 06:44 UTC, ymoog requested changes

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx-common/development/format_sd-card.rsti
>        host:~$ umount /mnt
You have to be careful here. This section explains how you can enlarge the root partition in order to later flash the image you copy here. When it is not a wic image but a compressed image like wic.xz flashing does not work the same because you need to decompress the image first.

In other words: 
Either make sure this image here cannot be a compressed image 
or
Change the manual where this image copied here is flashed to eMMC.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx-common/development/format_sd-card.rsti
>        host:~$ umount /mnt
Same here as above

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx-common/development/uuu.rsti
> +you will also need |yocto-imagename|-|yocto-machinename|.\ |yocto-imageext|.
Same as above. Need to ensure this is not compressed or change manual.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +   host:~$ dd if=|yocto-imagename|-|yocto-machinename|.|yocto-imageext| status=progress | ssh root@192.168.3.11 "dd of=/dev/mmcblk2 conv=fsync"
This dd command needs an uncompressed image!

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +|yocto-imagename|.|yocto-machinename|/|yocto-imageext|). Set the |ref-bootswitch| to SD Card.
Does this substitution work?

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +      |yocto-imagename|-|yocto-machinename|.|yocto-imageext|
Again same issue with compressed images.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +      target:~$ dd if=|yocto-imagename|-|yocto-machinename|.|yocto-imageext| of=/dev/mmcblk2 conv=fsync
See dd comment above

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +   the WIC image (for example |yocto-imagename|.\ |yocto-imageext|) to this
Problem with compressed images

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +      u-boot=> fatload mmc 1:3 ${loadaddr} |yocto-imagename|-|yocto-machinename|.|yocto-imageext|
Problem with compressed images.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +*  Flash your WIC image (for example |yocto-imagename|.\ |yocto-imageext|)
Problem with compressed images.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +      |yocto-imagename|-|yocto-machinename|.|yocto-imageext|
Problem with compressed images.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +         target:~$ dd if=|yocto-imagename|-|yocto-machinename|.|yocto-imageext| of=/dev/mmcblk2 conv=fsync
Problem with compressed images.

2024-04-10 06:44 UTC, ymoog commented on source/bsp/getting-started.rsti
> +   host:~$ sudo partup install |yocto-imagename|-|yocto-machinename|.|yocto-imageext-partup| /dev/<your_device>
Do you think it is a good idea to do this? Maybe we should look at the .rootfs. change first and figure out if that is something we want in the future.

2024-04-10 07:29 UTC, mschwan-phytec commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-imageext-partup| replace:: rootfs.partup
See https://git.yoctoproject.org/poky/commit/?id=6f6c79029bc2020907295858449c725952d560a1

2024-04-10 13:52 UTC, Varakala02 commented on source/bsp/getting-started.rsti
> +   host:~$ xzcat |yocto-imagename|-|yocto-machinename|.|yocto-imageext|.xz | sudo dd of=/dev/<your_device> bs=1M conv=fsync status=progress
I think using two different substitutions one for compressed and one for uncompressed image extension might help to solve this problem.

2024-04-10 13:53 UTC, Varakala02 commented on source/bsp/imx-common/development/format_sd-card.rsti
>        host:~$ umount /mnt
I think using two different substitutions one for compressed and one for uncompressed image extension might help to solve this problem.

2024-04-11 05:56 UTC, ymoog commented on source/bsp/imx-common/development/format_sd-card.rsti
>        host:~$ umount /mnt
Can you show this with an example, please.

2024-04-16 10:56 UTC, Varakala02 commented on source/bsp/imx-common/development/format_sd-card.rsti
>        host:~$ umount /mnt
I have updated by moving the files into the imx8mp directory and not proceeding with the new substitution variables.

2024-04-16 13:49 UTC, Varakala02 commented
> @Varakala02 as mainline-head is the only one special here I would prefer that you copy the content of the files to there instead of creating new imx8mp/*.rsti files.

Agree, I will update it.

2024-04-17 07:14 UTC, ymoog approved these changes

2024-04-17 10:48 UTC, BHahn42618 submitted a review, later dismissed

2024-04-17 11:33 UTC, tremmet requested changes
Please make sure that the changes from https://github.com/phytec/doc-bsp-yocto/pull/177 are included when you copy the content into mainline-head.

2024-04-17 12:55 UTC, Varakala02 commented
> Please make sure that the changes from #177 are included when you copy the content into mainline-head.

Yeah, I have updated.

2024-04-22 06:26 UTC, tremmet approved these changes

2024-04-23 07:17 UTC, BHahn42618 approved these changes

2024-04-23 07:54 UTC, tremmet commented
@mschwan-phytec @jonas-rem from our side this pull request is fine now. Yannic previously already approved it. But he is not in office atm.

2024-04-23 08:17 UTC, mschwan-phytec commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +*  Flash your WIC image (for example |yocto-imagename|.\ |yocto-imageext|)
I haven't checked the output, but why is escaping needed here? In code-blocks you do not escape the substitution. Is it actually needed in normal flow-text?

2024-04-23 08:49 UTC, Varakala02 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +*  Flash your WIC image (for example |yocto-imagename|.\ |yocto-imageext|)
Actually, this part is not inside the code-blocks so I had to use the substitution in this way.

2024-04-23 08:59 UTC, mschwan-phytec commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +*  Flash your WIC image (for example |yocto-imagename|.\ |yocto-imageext|)
Okay. Is it because of the preceding dot? Because `|yocto-imagename|` and `|yocto-imagename|-|yocto-machinename|` do not use a backslash.

2024-04-23 09:29 UTC, Varakala02 commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +*  Flash your WIC image (for example |yocto-imagename|.\ |yocto-imageext|)
Yes, it is because of the preceding dot. When two substitutes are separated by hyfen (-) it is working but when used dot, it fails and need to use backslash.

2024-04-23 09:38 UTC, merged