Wip/bhahn/BSPIMX8M-3208: bsp: imx8: rework EEPROM chapter
phytec/doc-bsp-yocto pull request #176
Opened 2024-04-16 08:53 UTC by BHahn42618

Based on BSPIMX8M-3205 =>probably needs rebase when that is merged. => only the last commit is new

Update description at the beginning. There are not two EEPROMs it is one
with two different addresses.
    
Starting with PD24.1.0 the EEPROM ID-page will not be accessible via the
sysfs anymore. Change that in the description. Update command for
restoring 0x51 EEPROM to U-Boot.
    
Remove the "Rescue EEPROM Data" chapter for new manuals and dissolve it
for PD22.1.1 and PD23.1.0. The command does not work for newer versions.
For newer versions move the note to contact our support to the top.

2024-04-16 09:31 UTC, tremmet submitted a review, later dismissed

2024-04-17 11:32 UTC, ymoog approved these changes

2024-04-17 12:16 UTC, jonas-rem commented
@BHahn42618 #174  is merged, you can rebase now.

2024-04-17 18:02 UTC, jonas-rem requested changes

2024-04-17 18:02 UTC, jonas-rem commented on source/bsp/imx8/imx8mn/head.rst
> +(bus: I2C-0 address: 0x59) are used for board detection and should not be
s/should/must

Please check also further occurences of should in the other files.

2024-04-23 07:11 UTC, BHahn42618 commented on source/bsp/imx8/imx8mm/pd22.1.1.rst
> +address: 0x59) can be accessed via the sysfs interface in Linux. The first
Yes in PD22.1.1 and PD23.1.0 the ID-Page can be accessed via sysfs. In PD24.1.0 (upstream release) it can not be accessed and we decided to do this for future BSPs.

2024-04-23 08:38 UTC, tremmet approved these changes

2024-04-23 10:15 UTC, jonas-rem approved these changes

2024-04-23 10:15 UTC, merged