BSPIMX8M-3204: Descibe partup issue due to new default option in resize2fs
phytec/doc-bsp-yocto pull request #177
Opened 2024-04-16 11:39 UTC by tremmet

Flashing a partup images created with Yocto versions mickledore or newer do not work when the systems resize2fs version is, too old (1.46.6 and older).

The newest E2fsprog versions has a new default option enabled in the filesystem, which is not compatible with older versions. 
https://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.47.0

As we support Ubuntu 22.04 as host system we do see the issue there.

Make flashing an SD-Card from host with bmap as first option in the documentation and add a note in the partup section.
As the same issue appears when using gparted and a note there, too.

2024-04-16 12:04 UTC, mschwan-phytec requested changes

2024-04-16 12:04 UTC, mschwan-phytec commented on source/bsp/getting-started.rsti
> +   *partup* running on host systems which are using resize2fs version 1.46.6 and older
The sentence is a little weird to read, IMHO. I think it can be easily fixed by removing the following part at the beginning:
```suggestion
   Host systems which are using resize2fs version 1.46.6 and older
```

2024-04-16 12:04 UTC, mschwan-phytec commented on source/bsp/getting-started.rsti
> +   or newer to SD-Card. This is due to a new default option in resize2fs which causes a
"a**n** incompatibility"
```suggestion
   or newer to SD-Card. This is due to a new default option in resize2fs which causes an
```

2024-04-16 12:04 UTC, mschwan-phytec commented on source/bsp/getting-started.rsti
> +   (e.g. Ubuntu 22.04) are not able to write a partup image created with Yocto Mickledore
`s/partup image/partup package/g`
We should be consistent with the naming of "partup packages".
```suggestion
   (e.g. Ubuntu 22.04) are not able to write partup packages created with Yocto Mickledore
```

2024-04-17 07:23 UTC, ymoog approved these changes

2024-04-17 07:27 UTC, BHahn42618 approved these changes

2024-04-17 09:34 UTC, mschwan-phytec commented on source/bsp/getting-started.rsti
> +   incompatibility.
I also noticed that. :confused:

2024-04-17 09:34 UTC, mschwan-phytec approved these changes
Thanks for the changes!

2024-04-17 09:34 UTC, merged