contributing
phytec/doc-bsp-yocto pull request #178
Opened 2024-04-17 14:47 UTC by Varakala02

2024-11-08 09:49 UTC, jonas-rem requested changes
@Varakala02 do you still work on this? If not, I would close it for now.

2024-11-08 09:49 UTC, jonas-rem commented on CONTRIBUTING.rst
> +example is below.
You were describing an example, but as of now there is no example.

2024-11-13 11:28 UTC, Varakala02 commented on CONTRIBUTING.rst
> +example is below.
Hi @jonas-rem Sorry, I totally forgot this, thank you. I will update it.

2024-11-13 16:40 UTC, jonas-rem requested changes

2024-11-13 16:40 UTC, jonas-rem commented on CONTRIBUTING.rst
> +------------------------------------------------------
The underline length should match the text length.

Otherwise looks good.

2024-11-14 15:27 UTC, jonas-rem approved these changes

2024-11-14 15:27 UTC, merged