BSPIMX8M-3167:  Create i.MX8MP PD24.1.0 documentation
phytec/doc-bsp-yocto pull request #179
Opened 2024-04-24 12:24 UTC by tremmet

Create a i.MX8MP PD24.1.0 BSP Manual based on imx8mp mainline-head.

2024-04-25 07:19 UTC, BHahn42618 requested changes

2024-04-25 07:19 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/pd24.1.1.rst
> +.. |ref-usb-otg| replace:: :ref:`X5 (upper connector) <imx8mp-pd24.1.0-components>`
These substitutions are still on pd24.1.0 not pd24.1.1. This will probably not break anything, as there is no pd24.1.0 manual, but I think it is worth noting.

2024-04-25 07:19 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/pd24.1.1.rst
> +.. |ref-jp4| replace:: :ref:`JP4 <imx8mp-pd24.1.0-components>`
Also here still on pd24.1.0 instead of pd24.1.1

2024-04-29 06:52 UTC, tremmet commented on source/bsp/imx8/imx8mp/pd24.1.1.rst
> +.. |ref-usb-otg| replace:: :ref:`X5 (upper connector) <imx8mp-pd24.1.0-components>`
Yes I missed that. Fixed it.

2024-04-29 12:05 UTC, BHahn42618 approved these changes

2024-04-30 11:48 UTC, jonas-rem approved these changes

2024-04-30 11:48 UTC, merged