Wip/andrej.picej@norik.com/bsp imx93 pd24.1.1
phytec/doc-bsp-yocto pull request #180
Opened 2024-04-25 10:55 UTC by andrejpicej

BSP manual for new upcoming i.MX93 PD24.1.1 release.

This release brings support for additional phyBOARD-Nash. Some peripherals differ between the two phyBOARD or are specific for phyBOARD Nash, this is noted and hopefully clear in the BSP manual.

TODO: still need to add phyBOARD Nash pictures with the last commit.

2024-04-29 08:47 UTC, tremmet commented
Commit message "bsp: peripherals: Add ADC chepter"  needs a typo fix.

2024-04-29 08:47 UTC, tremmet requested changes

2024-04-29 08:47 UTC, tremmet commented on source/bsp/peripherals/emmc.rsti
> +main storage. eMMC devices contain raw MLC or TLC combined with a memory
Maybe write out the full description of MLC and TLC during the first usage and the acronym in bracket. Like done for BKOPS below.

2024-04-29 08:47 UTC, tremmet commented on source/bsp/peripherals/adc.rsti
> +The PHYTEC |soc| include general purpose Analog-to-Digita Converters (ADC) which
s/Analog-to-Digita/Analog-to-Digital/g

2024-04-29 08:47 UTC, tremmet commented on source/bsp/imx8/imx8mm/head.rst
> +.. include:: /bsp/peripherals/rs232-485.rsti
I agree that the documentation chapter is really generic and can be moved to a common place. But to have it really generic I would suggest to split the file. As I can image that not all boards have RS232 and RS485 available.

2024-04-29 08:47 UTC, tremmet commented on source/bsp/imx9/imx93/peripherals/tpm.rsti
> +Here are some useful stuff to do with TPM:
Maybe better write: "Here are some useful examples to work with the TPM"

2024-05-06 06:11 UTC, andrejpicej commented on source/bsp/peripherals/emmc.rsti
> +main storage. eMMC devices contain raw MLC or TLC combined with a memory
Makes sense. Fixed.

2024-05-06 06:11 UTC, andrejpicej commented on source/bsp/peripherals/adc.rsti
> +The PHYTEC |soc| include general purpose Analog-to-Digita Converters (ADC) which
Fixed.

2024-05-06 06:11 UTC, andrejpicej commented on source/bsp/imx8/imx8mm/head.rst
> +.. include:: /bsp/peripherals/rs232-485.rsti
Split and updated.

2024-05-06 06:12 UTC, andrejpicej commented
> Commit message "bsp: peripherals: Add ADC chepter" needs a typo fix.

Fixed this and all other remarks. Thanks for your review :)

2024-05-06 07:21 UTC, tremmet approved these changes

2024-05-06 07:26 UTC, BHahn42618 approved these changes

2024-05-09 05:30 UTC, andrejpicej commented
Rebased to main

2024-05-13 06:54 UTC, pfiser approved these changes

2024-05-13 06:59 UTC, andrejpicej commented
@jonas-rem Can you merge this, please?

2024-05-13 08:57 UTC, merged