BSPIMX8M-2758: Update imx8 mainline HEAD for flashing wic.xz images
phytec/doc-bsp-yocto pull request #186
Opened 2024-06-10 07:26 UTC by ymoog

For the next mainline release, imx8 will switch to using compressed (wic.xz) OS images.

To this extent, the mainline-head imx8mp document needs to be changed.

- When flashing an image using dd, image needs to be decompressed first
- When flashing an image through the bootloader shell, image need to be decompressed first.
- Image filename extension will be updated.
- update list of files generated through the build system
- update misc. hardcoded .wic image names where necessary

2024-06-11 06:50 UTC, tremmet requested changes

2024-06-11 06:50 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
I would use here `|yocto-imageext|` instead of `wic.*`. This prevents any confusion.

What about the "rootfs" in the image name here?

2024-06-11 06:50 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
What about `rootfs` in the image name here?

2024-06-11 06:50 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +      |yocto-imagename|-|yocto-machinename|.wic.bmap
rootfs in the image name?

2024-06-11 07:13 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
I used wic.* because the bmap should be copied along with the image.

> What about the "rootfs" in the image name here?

It is not clear if we will keep rootfs in the image name (see internal discussions). As a result, I left it as is.

2024-06-11 07:27 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
> I used wic.* because the bmap should be copied along with the image.

Allright.
> 
> > What about the "rootfs" in the image name here?
> 
> It is not clear if we will keep rootfs in the image name (see internal discussions). As a result, I left it as is.

But it is only important if it makes into the BSP or? So you want to wait and update later? With this state we have to update it for sure. Whatever the outcome is.

2024-06-11 08:26 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
Yes. When we start working on the next Vendor BSP, we will need to either add rootfs to this doc or remove it in our Yocto layer.

2024-06-11 14:38 UTC, Varakala02 approved these changes

2024-06-12 08:02 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
> > What about the "rootfs" in the image name here?
> 
> It is not clear if we will keep rootfs in the image name (see internal discussions). As a result, I left it as is.

Apologies, rootfs should be included in this file, because it is necessary for the next PD24.1.2 release. In the other occasions for the non-mainline version not including rootfs remains correct.

2024-06-12 08:54 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +   target:~$ scp <USER>@192.168.3.10:/srv/tftp/|yocto-imagename|-|yocto-machinename|.wic.* /tmp && bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2
Okay we will only add the rootfs in mainline-head for now.

2024-06-12 08:55 UTC, tremmet commented on source/bsp/imx8/installing-os.rsti
> +      |yocto-imagename|-|yocto-machinename|.wic.bmap
Same here. Change only for mainline head.

2024-06-12 08:56 UTC, tremmet submitted a review, later dismissed

2024-06-13 09:24 UTC, mschwan-phytec requested changes

2024-06-17 12:32 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> -   partitions: (mmcblk2boot0; mmcblk2boot1)
In short: I deemed this unnecessary and inconsistent for the flashing explanation. 

When we hardcode the device in the next section just after this one, what use does this ``ls /dev`` have? It may be useful for general explanation of how block devices are displayed in Linux, but I found it rather confusing since nothing said here has any impact on the instructions to be executed.

2024-06-17 12:32 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> -   partitions: (mmcblk2\ **boot0**; mmcblk2\ **boot1**)
Same reasoning as above.

2024-06-17 12:44 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +
Users may choose their preferred path:

> If you do not have this set up, you need to adjust the
paths that point to the images being used in the instructions.

---
> What let to this decision?

The fact, that more commands may be copied as is. Fewer modifications to the supplied commands are necessary this way. Also, consistency.

Let's look at an example:

```diff
-   host:~$ dd if=|yocto-imagename|-|yocto-machinename|.|yocto-imageext| status=progress | ssh root@192.168.3.11 "dd of=/dev/mmcblk2 conv=fsync"
+   host:~$ scp /srv/tftp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| root@192.168.3.11:/tmp && ssh root@192.168.3.11 "bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2"
```

Before, you needed to change directory to where the image is located. 
Now, copy command as is.


To expand further: We have a mixture of relative path, i.e. ``cp <image> /someplace/else`` and placeholder ``cp <path/to/image>/image /someplace/else``. 
One could make the argument to use relative paths for every command, however I found using an absolute path more robust (no need to pay attention the cwd). 
Also, when/if using netboot/TFTP, images are already at a predefined location. This location may easily be reused.

2024-06-17 12:45 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
> +   |yocto-imagename|-|yocto-machinename|.wic.bmap
> Did you mean `ls /srv/tftp`? Anyhow, please read my other comment above on using this path, first.

yep, messed that up.

2024-06-17 12:48 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +and send it with ssh through the network to the eMMC of the target with a
Strictly speaking, it is not clear whether the image had been compressed before, so using uncompressed would be fine.

In the context of the release, we only supply compressed images. So, unless an umcopressed image had been generated at another point, it is safe to assume the image referred to here had to have been compressed.

I'll allow it.

2024-06-20 12:49 UTC, tremmet requested changes

2024-06-20 12:49 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   host:~$ scp /srv/tftp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| root@192.168.3.11:/tmp && ssh root@192.168.3.11 "bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imagee
```suggestion
   host:~$ scp /srv/tftp/|yocto-imagename|-|yocto-machinename|.rootfs.wic.* root@192.168.3.11:/tmp && ssh root@192.168.3.11 "bmaptool copy /tmp/|yocto-imagename|-|yocto-machinename|.|yocto-imageext| /dev/mmcblk2"
```

2024-06-25 06:10 UTC, ymoog commented on source/bsp/getting-started.rsti
> +Flash an uncompressed WIC image to SD card by calling:
I did that because I did not want to alter the manual where not necessary. However, since bmaptool does not care whether the image is compressed or not we can leave it as is. Good point, thanks!

2024-06-25 06:24 UTC, ymoog commented on source/bsp/getting-started.rsti
> +Flash an uncompressed WIC image to SD card by calling:
I used the same convention as for the optional ?(.rootfs) to support .wic and .wic.xz.

2024-06-25 08:40 UTC, tremmet submitted a review, later dismissed

2024-06-26 11:01 UTC, tremmet approved these changes

2024-06-26 12:45 UTC, Varakala02 approved these changes

2024-06-26 13:12 UTC, jonas-rem approved these changes
I did not found showstoppers in the unresolved conversations, so I will merge the PR. We can always open a follow-up PR to continue to discuss those issues and find optimal solutions.

2024-06-26 13:12 UTC, merged