BSPIMX8M-3107: Add fix RAM size documentation for Mainline HEAD
phytec/doc-bsp-yocto pull request #189
Opened 2024-06-17 08:53 UTC by tremmet

With the upcoming PD24.1.2 we will support different RAM sizes and RAM speed grades for i.MX8MP. 
RAM sizes and speed are either auto detected using EEPROM data or can be set to a fixed value during build time.

To explain how to configure the RAM to fix values for PD24.1.2 make use of the imx-common standalone_build.rsti chapter first.

As the common chapter still contains imx93 specific stuff add more substitutions to make it generic. 
Switch then all imx8 versions, to this generic file.

Then make some more adaptions to have things correct for the i.MX8MP mainline BSPs PD24.1.1 and PD24.1.2.

2024-06-18 09:53 UTC, ymoog requested changes

2024-06-18 09:53 UTC, ymoog commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +   CONFIG_PHYCORE_IMX8MP_USE_2GHZ_RAM_TIMINGS=y
Is this not outdated?

We have RAM_SIZE_FIX and RAM_FREQ_FIX.  As far as I understand the USE_2GHZ_RAM_TIMINGS would not have any effect because it depends on RAM_FREQ_FIX.

2024-06-18 11:27 UTC, ymoog submitted a review, later dismissed

2024-06-18 11:44 UTC, BHahn42618 approved these changes

2024-06-27 09:39 UTC, tremmet commented
Rebased everything on master.

2024-07-01 11:13 UTC, tremmet commented on source/bsp/imx-common/development/standalone_build_preface.rsti
> +   HTTP or HTTPS instead (e.g. git clone |u-boot-repo-url|)
Mhmm repositories URLs linked to our own git and not github can not be opened in a browser. So having a web link here may confuse.

2024-07-01 11:14 UTC, tremmet commented
Rebased again to main.

2024-07-01 11:26 UTC, ymoog approved these changes

2024-07-01 11:46 UTC, BHahn42618 approved these changes

2024-07-01 12:01 UTC, tremmet commented
@jonas-rem @mschwan-phytec please merge soon so we can finish up the BSP documentation for i.MX8MP PD24.1.2 Mainline release.

2024-07-01 12:21 UTC, merged