BSPIMX8M-3258 Update links and tags to BSP mainline documentation
phytec/doc-bsp-yocto pull request #198
Opened 2024-06-27 08:05 UTC by ymoog

Update links to
1. PHYTEC Website
2. PHYTEC Download Server
3. device tree nodes

2024-06-27 09:45 UTC, tremmet requested changes

2024-06-27 09:45 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-bootenv-link| replace:: :yocto-bootenv:`scarthgap`
Can you fix this also for PD24.1.1?

2024-06-27 09:45 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-codename| replace:: scarthgap
Same here.

2024-06-27 09:45 UTC, tremmet commented on source/bsp/imx8/imx8mp/mainline-head.rst
> +.. |yocto-ref-manual| replace:: Yocto Reference Manual (scarthgap)
And here.

2024-07-01 06:11 UTC, tremmet approved these changes

2024-07-01 09:17 UTC, jonas-rem approved these changes

2024-07-01 09:17 UTC, merged