Wip/bhahn/BSPIMX8M-3316
phytec/doc-bsp-yocto pull request #201
Opened 2024-07-05 14:39 UTC by BHahn42618

Port some updates that where done for mainline bsps also over to head for the upcoming NXP BSP.
- update from kirkstone to scarthgap
- new image ending rootf.wic.xz
- some general improvements

2024-07-08 09:34 UTC, tremmet approved these changes

2024-07-08 09:49 UTC, ymoog requested changes

2024-07-08 09:49 UTC, ymoog commented on source/bsp/imx8/installing-os.rsti
Is this now the same as mainline releases? I.e. can we include this in PD24.x?

2024-07-08 09:49 UTC, ymoog commented on source/bsp/imx8/imx8mm/head.rst
> +.. |yocto-headless-imagename| replace:: phytec-headless-image
I don't think this is necessary. The name is very unlikely to ever change. Even if it does, the frequency of changes to this name will be non-existent. Anyway, the "alias" is even longer than the name, just hardcode it.

2024-07-08 09:50 UTC, ymoog commented
You are touching imx93 files. You should ask imx9 maintainers for review! I will include them.

2024-07-11 10:52 UTC, tremmet approved these changes

2024-07-12 05:51 UTC, ymoog approved these changes

2024-07-12 07:56 UTC, merged