BSPIMX8M-3281: bsp: imx-common: standalone_build_kernel: Add note to the kernel build
phytec/doc-bsp-yocto pull request #202
Opened 2024-07-08 15:07 UTC by Varakala02

To build the standalone kernel successfully by overcoming the openssl error, need to install the libssl-dev package. So, a note in detail is added inthe standalone kernel chapter.

2024-07-09 05:10 UTC, ymoog requested changes

2024-07-09 05:10 UTC, ymoog commented on source/bsp/imx-common/development/standalone_build_kernel.rsti
> +
Please add this to the list in ``standalone_build_preface`` instead.

2024-07-10 09:39 UTC, Varakala02 commented on source/bsp/imx-common/development/standalone_build_kernel.rsti
> +
Updated, thanks

2024-07-10 10:56 UTC, ymoog approved these changes

2024-07-10 12:42 UTC, tremmet approved these changes

2024-07-11 07:31 UTC, merged