BSPIMX8M-3377 i.MX8MP-PD22.1.2 BSP manual
phytec/doc-bsp-yocto pull request #209
Opened 2024-08-02 12:40 UTC by ymoog

Create PD22.1.2 BSP manual based on the PD22.1.1 BSP manual. 

- Adjust all the external links.
- Adjust Kernel and U-Boot tag
- Adjust internal references
- Adjust BSP version and release date

Wait for merge until PD22.1.2 is released for all the external links to work.

2024-08-02 12:59 UTC, BHahn42618 requested changes

2024-08-02 12:59 UTC, BHahn42618 commented on source/conf.py
> +        'i.MX 8M Nano BSP Manual',
Why do you create a pd22.1.2 manual for the imx8mp and then write here that it is for nano?

2024-08-05 09:16 UTC, BHahn42618 submitted a review, later dismissed

2024-08-05 11:07 UTC, Varakala02 submitted a review, later dismissed

2024-08-07 07:01 UTC, ymoog commented
@jonas-rem You may squash if you wish. I used 2 commits for better review-ability. Please also create a ``imx8mp-pd22.1.2`` tag on this last commit when merged to main.

2024-08-07 07:09 UTC, jonas-rem commented
> @jonas-rem You may squash if you wish. I used 2 commits for better review-ability. Please also create a `imx8mp-pd22.1.2` tag on this last commit when merged to main.

Nice, this makes reviewing easier. I will keep it as is and not squash.

2024-08-07 07:10 UTC, jonas-rem approved these changes

2024-08-07 07:11 UTC, merged