BSPIMX8M-3356 document FIT image standalone build
phytec/doc-bsp-yocto pull request #213
Opened 2024-08-30 07:11 UTC by ymoog

We switch bootscript to FIT image as well as kernel+dt. Document changes needed when compiling kernel.

2024-08-30 13:43 UTC, BHahn42618 requested changes

2024-08-30 13:43 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/head.rst
> +   run boot_command
```suggestion
   run legacyboot
   ```
   this got renamed to legacyboot

2024-09-02 07:21 UTC, tremmet requested changes

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/development/kernel.rsti
> +be packaged in a FIT image for U-Boot to be able to boot it.
I would simplify the sentence somehow.

```suggestion
In consequence the standalone kernel image has to be packaged as a FIT image, too.
```

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/development/kernel.rsti
> +*  The Image can be found at ~/|kernel-repo-name|/arch/arm64/boot/Image
In the commands creating the fitImage below you are using the compressed image Image.gz. I think you should refer to this image there, too.

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/development/kernel.rsti
> +                     && ln -s arch/arm64/boots/Image.gz linux.bin
```suggestion
                     && ln -s arch/arm64/boot/Image.gz linux.bin
```

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/development/uboot.rsti
> +*  The **tag** needed at this release is called |u-boot-tag|
```suggestion
*  The **tag** used in this release is called |u-boot-tag|
```

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/imx8mp/head.rst
> +.. include:: ../development/kernel.rsti
I would prefer if the name of the files would contain information that they are about the standalone build.

2024-09-02 07:21 UTC, tremmet commented on source/bsp/imx8/imx8mp/head.rst
> +This way of booting is deprecated and will be removed in the next release.
Maybe add this to a info box?

2024-09-02 11:09 UTC, ymoog commented on source/bsp/imx8/development/kernel.rsti
> +*  The Image can be found at ~/|kernel-repo-name|/arch/arm64/boot/Image
Okay, will do

2024-09-02 11:34 UTC, ymoog commented on source/bsp/imx8/imx8mp/head.rst
> +.. include:: ../development/kernel.rsti
I suffixed the names with -standalone as the files contents are not limited to build instructions.

2024-09-03 06:27 UTC, tremmet requested changes

2024-09-03 06:27 UTC, tremmet commented on source/bsp/imx8/development/kernel-standalone.rsti
> +      host:~/|kernel-repo-name|$ make -j${nproc}
Can you fix this? :)

2024-09-03 06:53 UTC, tremmet approved these changes

2024-09-04 11:26 UTC, BHahn42618 approved these changes

2024-09-04 11:34 UTC, merged