Sphinx: add internationalization
phytec/doc-bsp-yocto pull request #215
Opened 2024-09-03 17:55 UTC by jonas-rem

This PR is a draft on how to add internationalization to the project. Pushing to test the GitHub actions compatibility. More information coming soon.

2024-09-23 12:27 UTC, ymoog requested changes
Please explain in your commit message a bit more background information.
E.g.
2nd commit: How to add more languages
3rd commit: with which command did you generate the commited changes and why did you do this? I.e. goal of the commit
4th commit: how and when does this .mo file get generated?
5th commit: you don't explain how other users may expand on this. How does this translation work? I don't see any added documentation in your commits, neither did you add any reference to instructions.

2024-09-23 12:27 UTC, ymoog commented on tox.ini
>      sphinx-build -M latex source build -W --keep-going -j auto
Why not change to ``build/latex/en``?

2024-09-25 14:50 UTC, jonas-rem commented on tox.ini
>      sphinx-build -M latex source build -W --keep-going -j auto
Yes, that cleans up the directory for the pdf files. For the generated html build I will keep it as is, since en is the default language for the website.

2024-10-14 08:28 UTC, ymoog approved these changes

2024-10-14 09:04 UTC, merged