Wip/bhahn/BSPIMX8M-3386 BSPIMX8M-3342
phytec/doc-bsp-yocto pull request #216
Opened 2024-09-13 11:04 UTC by BHahn42618

- remove old outdated hci info
- peb-av-10 overlay got renamed for new imx8mp PD24.1.0 NXP BSP
- add note that some boards might have multiple backlight controls

2024-09-16 06:38 UTC, ymoog approved these changes

2024-09-16 06:44 UTC, tremmet approved these changes

2024-09-16 21:17 UTC, jonas-rem requested changes

2024-09-16 21:17 UTC, jonas-rem commented on source/bsp/imx-common/peripherals/display.rsti
> +   Some boards with multiple display connectors might have multiple multiple backlight
Remove one "multiple"

2024-09-17 07:48 UTC, jonas-rem approved these changes

2024-09-17 07:48 UTC, merged