bsp: imx-common: standalone_build_kernel: Fix indentation
phytec/doc-bsp-yocto pull request #218
Opened 2024-09-18 11:29 UTC by s-hemer

The code block wasn't correctly formatted. Fixes 9badff3380f40

2024-09-18 11:34 UTC, s-hemer commented
BTW this code block seems to be somehow out of context: bullet point before is "building kernel", following is about where to find the results. Imho installing kernel modules is an more advanced task and should go to the end of the list (behind re-building DTs)?!

2024-09-27 14:38 UTC, tremmet commented
> BTW this code block seems to be somehow out of context: bullet point before is "building kernel", following is about where to find the results. Imho installing kernel modules is an more advanced task and should go to the end of the list (behind re-building DTs)?! Potentially, this is also a duplicate info as it is part of the following section, so completely remove here?

Feel free to create a pull request or write a ticket in our jira project.

2024-09-27 14:39 UTC, tremmet commented
@s-hemer don't forget to add reviewers to your pull request :)

2024-09-27 14:40 UTC, tremmet approved these changes

2024-09-27 15:24 UTC, BHahn42618 requested changes

2024-09-27 15:24 UTC, BHahn42618 commented on source/bsp/imx-common/development/standalone_build_kernel.rsti
>    .. code-block:: console
This line is also missing one space.
```suggestion
   .. code-block:: console
```

2024-09-27 16:01 UTC, s-hemer commented on source/bsp/imx-common/development/standalone_build_kernel.rsti
>    .. code-block:: console
Fixed

2024-09-30 07:05 UTC, BHahn42618 approved these changes

2024-09-30 07:25 UTC, tremmet approved these changes

2024-09-30 07:54 UTC, merged