Wip/andrej.picej@norik.com/bspimx8 m 3351
phytec/doc-bsp-yocto pull request #221
Opened 2024-09-20 12:30 UTC by andrejpicej

Need to exclude PEB-AV-12 and tripple display support from next NXP BSP release.

Hope this makes sense. Not sure if this is easier then copying the whole display chapter to the base file of the release and modifying it there.

2024-09-25 13:51 UTC, BHahn42618 requested changes

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/display.rsti
> +.. supported-displays-marker-start
This is more about the supported display interfaces than the supported displays themselves.
```suggestion
.. supported-display-interfaces-marker-start

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/display.rsti
> +.. supported-displays-marker-end
```suggestion
.. supported-display-interfaces-marker-end

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/display.rsti
> +10'' edt,etml1010g0dka display for the |10inch-displays|.
This is not about the 10inch-displays we support. In the future we could support other displays. This is about the lvds display adapters we support.
```suggestion
10'' edt,etml1010g0dka display for the |lvds-display-adapters|.

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/head.rst
> +.. |10inch-displays| replace:: PEB-AV-10
```suggestion
.. |lvds-display-adapters| replace:: PEB-AV-10

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/head.rst
> +   :end-before: .. supported-displays-marker-start
```suggestion
   :end-before: .. supported-display-interfaces-marker-start

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/head.rst
> +   :start-after: .. supported-displays-marker-end
```suggestion
   :start-after: .. supported-display-interfaces-marker-end

2024-09-25 13:51 UTC, BHahn42618 commented on source/bsp/imx8/imx8mp/pd23.1.0.rst
> +.. |10inch-displays| replace:: PEB-AV-10 and PEB-AV-012
```suggestion
.. |lvds-display-adapters| replace:: PEB-AV-10 and PEB-AV-012

2024-09-26 05:59 UTC, tremmet approved these changes

2024-09-30 10:40 UTC, merged