i.MX93 PD24.2.0 update
phytec/doc-bsp-yocto pull request #228
Opened 2024-10-14 13:46 UTC by pfiser

Add i.MX93 documentation update for the PD24.2.0 release.

Changes:
- Component versions update (based on NXP lf-6.6.23-2.0.0)
- Rename PEB-AV-10 overlay
- Add additional overlays
- Bootloader unified defconfig
- Kernel defconfig changes
- Note about disabled VFS driver on 900MHz CPU
- Rename output images to contain ".rootfs."

2024-10-15 07:02 UTC, andrejpicej requested changes
Just a few comments and improvements. Otherwise LGTM.

2024-10-15 07:16 UTC, pfiser commented on source/bsp/imx9/imx93/pd24.2.0.rst
> +| Release Date          | 2024/01/31           |
Missed that, fixed

2024-10-15 07:17 UTC, pfiser commented on source/bsp/imx9/imx93/pd24.2.0.rst
> +
This has been noted in the releasenotes. I would not stress it further.

2024-10-15 07:25 UTC, pfiser commented on source/bsp/imx9/imx93/pd24.2.0.rst
> +.. |u-boot-tag| replace:: v2024.04-2.0.0-phy6
I think releasenotes is wrong here.

@cstoidner : Can you update releasenotes with v2024.04-2.0.0-phy6 tag for U-Boot?

2024-10-15 07:38 UTC, pfiser commented on source/bsp/imx9/imx93/pd24.2.0.rst
> +   *  phyBOARD-Nash-i.MX 93: 1616.0
@rstidronski : Should we put both Nash revisions here?

2024-10-15 08:27 UTC, rstidronski commented on source/bsp/imx9/imx93/pd24.2.0.rst
> +   *  phyBOARD-Nash-i.MX 93: 1616.0
@pfiser I would include the new PCB version. As long as we don't have heavy breaking changes we can also say "1616.x" or "1616.0 and later versions"

2024-10-16 06:01 UTC, pfiser commented
Added:

- WLAN chapter via PEB-WLBT-05 on Segin
- PWM fan chapter
- fix for |serial-uart| substitution
- Nash rev 1616.1 to bootmode switches

2024-10-29 13:43 UTC, cstoidner requested changes
Looks good. Only the order of the version should be changed (see comment).

2024-10-30 06:07 UTC, pfiser commented on source/bsp/imx9/imx93/imx93.rst
> +   pd24.2.0
Fixed it.

2024-10-31 14:06 UTC, jonas-rem approved these changes
You did not added the entries to conf.py to build the pdf versions and link the static links to access the pdf build the html website. I will do this as a second step after merging this PR. Afterwards we can apply the tag to fix the version in the repo.

I already tested: PDF build works for the new version in general.

2024-10-31 14:14 UTC, merged