BSPIMX8M-3496 adapt dt-overlays chapter to external boot script
phytec/doc-bsp-yocto pull request #230
Opened 2024-10-15 12:33 UTC by ymoog

Handling of device tree overlays changed due to introduction of loading and executing an external boot script.
As the boot script can be used for all PHYTEC products (using U-Boot) make a generic include file for overlay handling.
The new file is mostly a copy of the existing imx8 one, but does not contain any product specific info (examples include a specific expansion board, though).

2024-10-16 09:23 UTC, BHahn42618 requested changes

2024-10-16 09:23 UTC, BHahn42618 commented on source/bsp/dt-overlays.rsti
> +~~~~~~~~~~~~~~~~~
The extension command is used for legacy boot way. For fitimage boot, there is a function called `phytec_set_fit_extensions` in the board code, which sets the variable `fit_extensions` in the uboot environment. The same overlays should appear there as in the extension command, but they are formatted like in the overlays variable with `conf-overlayname1#conf-onverlayname2`. The `setenv no_extensions 1` command will also work for fitimage boot though.

2024-10-16 11:30 UTC, ymoog commented on source/bsp/dt-overlays.rsti
> +~~~~~~~~~~~~~~~~~
The function is specific for imx8mp an as such not fit for inclusion here. Should we leave that section out for now?

2024-10-17 08:35 UTC, BHahn42618 commented on source/bsp/dt-overlays.rsti
> +~~~~~~~~~~~~~~~~~
I think we should still describe, that some overlays that can be detected via eeprom get loaded automatically and that the loading mechanism can be disabled by setting no_extensions.
You are correct however. The mechanism how we did it is imx8 specific and should not be in this chapter.

2024-10-21 06:27 UTC, ymoog commented on source/bsp/dt-overlays.rsti
> +   overlays=conf-|dt-carrierboard|-peb-eval-01.dtbo#|dtbo-peb-av-10|
Yes. Any name/overlay will do as it is an example.

2024-10-21 07:08 UTC, BHahn42618 approved these changes

2024-10-22 06:29 UTC, merged