BSPIMX8M-3424 bsp: imx8mp: Add chapter about booting efi
phytec/doc-bsp-yocto pull request #234
Opened 2024-10-18 12:47 UTC by BHahn42618

For the new PD24.1.0 release booting with efi is supported. Add a chapter on how to turn on/off booting with efi and how to install a distro and boot it with efi.

2024-10-21 07:13 UTC, ymoog requested changes

2024-10-21 07:13 UTC, ymoog commented on source/bsp/efi.rsti
> +for a bootscript first, which is used to boot our Ampliphy distro. If it does not find any
This is imx8 specific behaviour, remove this please.

2024-10-21 07:13 UTC, ymoog commented on source/bsp/efi.rsti
> +To disable booting with efi you have to set the ``doefiboot`` variable to 0. Also make sure you
This is also imx8 specific, right?

2024-10-21 07:13 UTC, ymoog commented on source/bsp/efi.rsti
> +install.
Please describe in more detail what not to do. When will I overwrite the bootloader?

2024-10-21 07:13 UTC, ymoog commented on source/bsp/efi.rsti
> +That will open a menu. When you can select ``Edit Boot Option``. It will show you the current boot
```suggestion
That will open a menu. Then you can select ``Edit Boot Option``. It will show you the current boot
```

2024-10-22 10:27 UTC, BHahn42618 commented on source/bsp/efi.rsti
> +for a bootscript first, which is used to boot our Ampliphy distro. If it does not find any
Moved the imx8 specific part to imx8 folder

2024-10-22 10:27 UTC, BHahn42618 commented on source/bsp/efi.rsti
> +To disable booting with efi you have to set the ``doefiboot`` variable to 0. Also make sure you
Moved the imx8 specific part to imx8 folder

2024-10-22 10:27 UTC, BHahn42618 commented on source/bsp/efi.rsti
> +install.
Hope this is okay now

2024-10-23 06:20 UTC, ymoog approved these changes

2024-10-23 06:20 UTC, ymoog commented on source/bsp/efi.rsti
> +install.
Yes, looks good! Thanks

2024-10-23 06:56 UTC, tremmet commented on source/bsp/installing-distro-efi.rsti
> +for example to emmc (mmc2) or sdcard (mmc1). Make sure you do not overwrite your U-Boot during the
What about using substitutions for mmc2 and mmc1? So it makes it a little bit more generic and more ready to use for different platform.

2024-10-30 13:56 UTC, jonas-rem approved these changes
Waiting for one more review from the imx8 team to check contents before merging.

2024-10-31 07:10 UTC, tremmet approved these changes

2024-10-31 07:40 UTC, ymoog approved these changes

2024-10-31 09:54 UTC, merged