Wip/bhahn/rs485 update
phytec/doc-bsp-yocto pull request #240
Opened 2024-10-29 14:16 UTC by BHahn42618

Update rs485 chapter to have much more detailed documentation on how to test rs485.

2024-10-29 16:52 UTC, jonas-rem requested changes

2024-10-29 16:52 UTC, jonas-rem commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +You should see "test" printed out on target1. You can also switch the roles and send on target2
Looks like a textwidth of more than 80 character. Can you re-format to max 80 characters wherever possible?

2024-10-30 07:15 UTC, ymoog requested changes

2024-10-30 07:15 UTC, ymoog commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +To see which pin has which function check the hardware manual.
This is not true. For RS232, the same principle applies.
Also, please choose more technical terms than "crossed" and "straight" (you don't have to replace the terms, you can rephrase which I think is more appropriate here).
Note that you need to differentiate between master and slave device. When you have multiple masters, then both their tx+ are connected to a slaves rx+ (For simple 2 device setups you always have master and slave).

2024-10-30 07:15 UTC, ymoog commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +difference in time with the ``-W 2`` option. At the end the program will print the final
```suggestion
received. Remember to start both targets almost simultaneously. A small
difference in start time is accounted for with the ``-W 2`` option. At the end the program will print the final
```

2024-10-30 07:15 UTC, ymoog commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +"count for this session". There you can check, that all transmitted frames were received.
No comma here.

2024-10-30 07:15 UTC, ymoog commented on source/bsp/peripherals/rs485.rsti
> +
Put this as ``note`` or ``hint`` ?

2024-10-30 10:49 UTC, BHahn42618 commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +You should see "test" printed out on target1. You can also switch the roles and send on target2
Ah ok, I formatted to 100 characters per line (like in ptf). Will do

2024-10-30 13:19 UTC, BHahn42618 commented on source/bsp/peripherals/rs485-fullduplex.rsti
> +To see which pin has which function check the hardware manual.
I have removed this passage and put another picture on how to do the wiring here instead.

2024-10-31 07:38 UTC, ymoog approved these changes

2024-10-31 09:33 UTC, merged