BSPIMX8M-3483 bsp: imx8: add how to switch back to legacyboot
phytec/doc-bsp-yocto pull request #245
Opened 2024-11-04 14:45 UTC by BHahn42618

For imx8mp NXP PD24.1.0 we switched to standardboot and booting the kernel from a fitimage. We decided to keep the possibility to easily switch back to the old method of booting (legacyboot). This option is marked as depricated and will be removed in the future. Add a chapter on how to switch back to legacyboot.

2024-11-05 06:56 UTC, ymoog commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +the end it should look something like this:
I suggest to use formal expressions as you are not explaining something to your good friend, but to customers who you have a formal relationship with.

2024-11-05 06:56 UTC, ymoog commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +To re-enable legacyboot you need to set the following variable:
```suggestion
To re-enable legacyboot set the following variable:
```

2024-11-05 09:10 UTC, ymoog commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +example in the file `conf/machine/phyboard-pollux-imx8mp-3.conf` in
Why do require this new variable thing with different dt names?

In previous releases we didn't need that, why now?

2024-11-05 09:44 UTC, BHahn42618 commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +example in the file `conf/machine/phyboard-pollux-imx8mp-3.conf` in
In previous releases we had the EXTERNAL_DEVICETREE variable, that had all the devicetrees in it. However this seems to not exist anymore or is not set anymore, so we need to create a variable for that.

2024-11-06 07:38 UTC, tremmet requested changes

2024-11-06 07:38 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +Edit this file: `conf/machine/include/phyimx8m.inc` in meta-phytec and edit the
It would be better to describe how to change it in the local.conf or a custom layer. meta-phytec should not be touched.

2024-11-06 07:38 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +example in the file `conf/machine/phyboard-pollux-imx8mp-3.conf` in
Are you sure it was called like that (EXTERNAL_DEVICETREE)? I can not find it in the history. 

But the same as above. Explain how to change this in local.conf or a custom layer.

2024-11-06 07:50 UTC, ymoog commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +example in the file `conf/machine/phyboard-pollux-imx8mp-3.conf` in
EXTERNAL_KERNEL_DEVICETREE.

2024-11-06 08:27 UTC, BHahn42618 commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +example in the file `conf/machine/phyboard-pollux-imx8mp-3.conf` in
Yes, EXTERNAL_KERNEL_DEVICETREE is the one I meant

2024-11-06 13:04 UTC, BHahn42618 commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +Edit this file: `conf/machine/include/phyimx8m.inc` in meta-phytec and edit the
I agree. I changed it to local.conf.

2024-11-07 14:36 UTC, tremmet requested changes

2024-11-07 14:36 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +By default, the fitImage and bootscript will be deployed into the Image.
```suggestion
By default, the fitImage and bootscript will be deployed into the wic.xz Image.
```

2024-11-07 14:36 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +To switch back to legacyboot, you need to switch the fitImage and bootscript
```suggestion
To switch back to legacyboot, you need to replace the fitImage and bootscript
```

2024-11-07 14:36 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +for the kernel image and the devicetrees. They will still be in the deploy
```suggestion
for the kernel image and the devicetrees. They are still in the deploy
```

2024-11-07 14:36 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +      bitbake -c cleanall |yocto-imagename|
Maybe add how to then start the build again then, too.

2024-11-07 14:36 UTC, tremmet commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +   uboot=> env save; env save;
And the command line to start the boot.

2024-11-07 15:45 UTC, BHahn42618 commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +      bitbake -c cleanall |yocto-imagename|
Done.

2024-11-07 15:45 UTC, BHahn42618 commented on source/bsp/imx8/development/legacy_boot_deprecated.rsti
> +   uboot=> env save; env save;
Done.

2024-11-08 08:48 UTC, ymoog approved these changes

2024-11-08 09:47 UTC, merged