BSPIMX8M-3299 bsp: imx8mp: update head for PD24.1.0 NXP release
phytec/doc-bsp-yocto pull request #247
Opened 2024-11-07 12:26 UTC by BHahn42618

Update all links, as well as the U-Boot and Kernel tags for the new NXP PD24.1.0 release.

2024-11-07 13:05 UTC, ymoog commented on source/bsp/imx8/imx8mp/head.rst
>  .. |kernel-repo-url| replace:: git://git.phytec.de/linux-imx
Is this correct? Thought we switched to linux-phytec-imx. I don't know if fixing this is within scope of your PR/task.

2024-11-07 14:08 UTC, tremmet requested changes

2024-11-07 14:08 UTC, tremmet commented on source/bsp/imx8/imx8mp/head.rst
>  .. |kernel-repo-url| replace:: git://git.phytec.de/linux-imx
Yes, please fix this here.

2024-11-07 14:35 UTC, tremmet approved these changes

2024-11-08 06:56 UTC, ymoog approved these changes

2024-11-08 09:46 UTC, merged