Add RAUC manuals
phytec/doc-bsp-yocto pull request #256
Opened 2024-11-26 09:56 UTC by landerweit-phytec

Add RAUC manuals for kirkstone, mickledore and scarthgap.

2024-11-28 06:32 UTC, mschwan-phytec requested changes
Thank you for porting the manual! :blush: Looks good overall!

There are only some minor things below...

2024-11-28 10:14 UTC, landerweit-phytec commented on source/rauc/kirkstone.rst
> +   compatible=phyboard-polis-imx8mm-4
Done

2024-11-28 10:17 UTC, landerweit-phytec commented on source/conf.py
> +        'rauc_kirkstone.tex',
Done

2024-11-28 10:18 UTC, landerweit-phytec commented on README.rst
> +   apt install latexmk texlive-xetex texlive-latex-extra texlive-lang-chinese
Done. New PR: #259

2024-11-29 07:36 UTC, mschwan-phytec approved these changes

2024-11-29 07:36 UTC, merged